# Generated by Django 4.2.7 on 2024-10-23 22:36

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seleccionada', models.DateField()),
                ('inicio', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('idFicha', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_ultima_consulta', models.DateField(null=True)),
                ('motivo_consulta', models.TextField(null=True)),
                ('sintomas_actuales', models.TextField(null=True)),
                ('diagnostico', models.TextField(null=True)),
                ('tratamiento_actual', models.TextField(null=True)),
                ('proxima_cita', models.DateField(null=True)),
                ('nombre_contacto_emergencia', models.TextField(null=True)),
                ('telefono_contacto_emergencia', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipoTratamiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreTratamiento', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_usuario', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='customuser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('rut', models.CharField(max_length=20, null=True, unique=True)),
                ('descripcion', models.TextField(null=True)),
                ('imageBlob', models.ImageField(blank=True, default='imagenes_usuario/profiledefault.jpg', null=True, upload_to='imagenes_usuario/')),
                ('fecha_nac', models.DateField(null=True)),
                ('num_tel', models.IntegerField(max_length=9, null=True)),
                ('direccion', models.TextField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_tipo_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProyectoAPT.tipousuario')),
                ('universidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProyectoAPT.universidad')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('inicio', models.TimeField()),
                ('fecha_seleccionada', models.DateField()),
                ('estudiante', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_estudiante', to=settings.AUTH_USER_MODEL)),
                ('ficha_clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProyectoAPT.fichaclinica')),
                ('paciente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_paciente_views', to=settings.AUTH_USER_MODEL)),
                ('tipoTratamiento', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProyectoAPT.tipotratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Medico',
            fields=[
                ('idHistorial', models.BigAutoField(primary_key=True, serialize=False)),
                ('medicamentos', models.TextField(null=True)),
                ('diagnostico', models.TextField(null=True)),
                ('fecha_cita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProyectoAPT.cita')),
                ('paciente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='paciente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichaclinica',
            name='tratamiento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProyectoAPT.tipotratamiento'),
        ),
        migrations.AddField(
            model_name='cita',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipotratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProyectoAPT.tipotratamiento'),
        ),
    ]
