# Generated by Django 4.2.7 on 2024-09-30 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='id',
            field=models.AutoField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoTratamiento', models.CharField(max_length=60)),
                ('HoraInicial', models.TimeField()),
                ('HoraFinal', models.TimeField()),
                ('fecha_seleccionada', models.DateField()),
                ('estudiante', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
