# Generated by Django 4.2.7 on 2024-11-04 19:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreComuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='horarios',
            options={'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='fecha_ultima_consulta',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='proxima_cita',
        ),
        migrations.AddField(
            model_name='cita',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProyectoAPT.universidad'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='Certificado',
            field=models.FileField(blank=True, help_text='Sube un certificado en formato PDF', null=True, upload_to='documentos_estudiantes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Solo se permiten archivos PDF')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tratamientos',
            field=models.ManyToManyField(blank=True, to='ProyectoAPT.tipotratamiento'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rut',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='tipoTratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProyectoAPT.tipotratamiento'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProyectoAPT.comuna'),
        ),
    ]
