# Generated by Django 4.2.7 on 2024-10-21 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Medico',
            fields=[
                ('idHistorial', models.BigAutoField(primary_key=True, serialize=False)),
                ('medicamentos', models.TextField(null=True)),
                ('diagnostico', models.TextField(null=True)),
                ('fecha_seleccionada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProyectoAPT.cita')),
                ('paciente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
