# Generated by Django 4.2.7 on 2024-09-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0002_alter_tipousuario_id_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
