# Generated by Django 4.2.7 on 2024-10-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0002_alter_customuser_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tratamientos',
            field=models.ManyToManyField(blank=True, to='ProyectoAPT.tipotratamiento'),
        ),
    ]
