# Generated by Django 4.2.7 on 2024-10-29 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0003_customuser_tratamientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Certificado',
            field=models.FileField(blank=True, help_text='Sube un certificado en formato PDF', null=True, upload_to='documentos_estudiantes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Solo se permiten archivos PDF')]),
        ),
    ]
