# Generated by Django 4.2.7 on 2024-10-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0003_rename_fecha_seleccionada_historial_medico_fecha_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_medico',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historial_medico',
            name='medicamentos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
