# Generated by Django 4.2.7 on 2024-10-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0004_customuser_certificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaclinica',
            name='fecha_ultima_consulta',
        ),
        migrations.RemoveField(
            model_name='fichaclinica',
            name='proxima_cita',
        ),
    ]
