# Generated by Django 4.2.7 on 2024-10-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0004_alter_historial_medico_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imageBlob',
            field=models.ImageField(blank=True, default='profiledefault.jpg', null=True, upload_to='imagenes_usuario/'),
        ),
        migrations.AlterField(
            model_name='historial_medico',
            name='diagnostico',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historial_medico',
            name='medicamentos',
            field=models.TextField(null=True),
        ),
    ]
