# Generated by Django 4.2.7 on 2024-10-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0005_alter_customuser_imageblob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='imageBlob',
            field=models.ImageField(blank=True, default='imagenes_usuario/profiledefault.jpg', null=True, upload_to='imagenes_usuario/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rut',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
