# Generated by Django 4.2.7 on 2024-10-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0005_remove_horarios_horafinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='imageBlob',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_usuario/'),
        ),
    ]
