# Generated by Django 4.2.7 on 2024-10-29 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0005_remove_fichaclinica_fecha_ultima_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProyectoAPT.universidad'),
        ),
    ]
