# Generated by Django 4.2.7 on 2024-10-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0006_cita_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
