# Generated by Django 4.2.7 on 2024-10-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0009_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('verificacion', models.BooleanField(default=False)),
            ],
        ),
    ]
