# Generated by Django 4.2.7 on 2024-10-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0009_alter_customuser_num_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreComuna', models.CharField(max_length=50)),
            ],
        ),
    ]
