# Generated by Django 4.2.7 on 2024-10-31 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0010_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProyectoAPT.comuna'),
        ),
    ]
