# Generated by Django 5.0.4 on 2024-10-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0013_cita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='tipo_tratamiento',
            new_name='tipotratamiento',
        ),
    ]
