# Generated by Django 4.2.7 on 2024-10-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0014_rename_tipo_tratamiento_cita_tipotratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('estado_civil', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('nombre_contacto_emergencia', models.CharField(max_length=100)),
                ('relacion_paciente', models.CharField(max_length=100)),
                ('telefono_contacto_emergencia', models.CharField(max_length=15)),
                ('fecha_ultima_consulta', models.DateField()),
                ('motivo_consulta', models.TextField()),
                ('sintomas_actuales', models.TextField()),
                ('diagnostico', models.TextField()),
                ('tratamiento_actual', models.TextField()),
                ('proxima_cita', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='direccion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='num_tel',
            field=models.IntegerField(null=True),
        ),
    ]
