# Generated by Django 4.2.7 on 2024-10-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0015_fichaclinica_customuser_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='diagnostico',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_ultima_consulta',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='motivo_consulta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre_contacto_emergencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='proxima_cita',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='relacion_paciente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sintomas_actuales',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono_contacto_emergencia',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tratamiento_actual',
            field=models.TextField(null=True),
        ),
    ]
