# Generated by Django 4.2.7 on 2024-10-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0016_customuser_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaclinica',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
