# Generated by Django 4.2.7 on 2024-10-18 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0019_rename_id_fichaclinica_idficha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarios',
            name='ficha_clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProyectoAPT.fichaclinica'),
        ),
    ]
