# Generated by Django 4.2.7 on 2024-10-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0020_horarios_ficha_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaclinica',
            name='tratamiento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProyectoAPT.tipotratamiento'),
        ),
    ]
