# Generated by Django 4.2.7 on 2024-10-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPT', '0021_fichaclinica_tratamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaclinica',
            name='diagnostico',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='fecha_ultima_consulta',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='motivo_consulta',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='nombre_contacto_emergencia',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='proxima_cita',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='sintomas_actuales',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='telefono_contacto_emergencia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fichaclinica',
            name='tratamiento_actual',
            field=models.TextField(null=True),
        ),
    ]
